[package]
name = "schreiber"
version = "0.1.0"
authors = ["jiisanda <harshjaiswal2307@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "2"
